wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.0
    cli_version: 0.15.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1691842712.443504
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 13
      - 23
      4: 3.8.0
      5: 0.15.5
      8:
      - 5
